### ISSUE TITLE
SyntaxError on self.account

### ISSUE THREAD

**Issue by clintm99** [stefanodvx/crunchyroll#5]
Hi,
My December 2021 version works good, but the Feb 9th version gives me:
`Python 3.7.9 (default, Aug 19 2020, 17:05:11) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from crunchyroll_beta import Crunchyroll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/crunchyroll-main/crunchyroll_beta/__init__.py", line 1, in <module>
    from .api import Crunchyroll
  File "/tmp/crunchyroll-main/crunchyroll_beta/api.py", line 124
    if expiration := self.account_data.expires:
                   ^
SyntaxError: invalid syntax
`
where api.py is.  
`11488  2月  9 11:59 crunchyroll_beta/api.py`

Thanks :)

**Comment by stefanodvx** [comment]
update pyhon to 3.8.9
